---
jgroups:
  encrypt: true
keystore:
  path: /server.jks
  password: changeit
  type: jks
  alias: 1
server:
  security:
    securityRealms:
      - name: "default"
        serverIdentities:
          ssl:
            keystore:
              path: "server.jks"
              password: "changeit"
              alias: 1
              provider: "BCFIPS"
              type: "BCFKS"