name: "Pull Request CI"
on:
  - pull_request
jobs:
  detect-test-suite-modules:
    name: Detect Modules in PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: files
        uses: tj-actions/changed-files@v37
        continue-on-error: true
      - id: detect-changes
        run: |
          MODULES=$(find -name pom.xml | sed -e 's|pom.xml| |' | sed -e 's|./| |' | grep -v " quarkus/")
          CHANGED=""
          MODULES_ARG=""

          for module in $MODULES
          do
            if [[ "${{ steps.files.outputs.all_changed_and_modified_files }}" =~ ("$module") ]] ; then
                CHANGED=$(echo $CHANGED" "$module)
                # trim leading spaces
                CHANGED="$(echo $CHANGED | xargs)"
                echo "changed in if is $CHANGED"
            fi
          done
          MODULES_ARG="${CHANGED// /,}"
          echo "modules arg are $MODULES_ARG"
          echo "MODULES_ARG=$MODULES_ARG" >> $GITHUB_OUTPUT
    outputs:
      MODULES_ARG: ${{ steps.detect-changes.outputs.MODULES_ARG }}
  detect-jvm-latest-modules-mvn-param:
    name: Detect Modules in PR
    runs-on: ubuntu-latest
    needs: [ detect-test-suite-modules ]
    env:
      MODULES_ARG: ${{ needs.detect-test-suite-modules.outputs.MODULES_ARG }}
    steps:
      - id: detect-modules-mvn-param
        run: |
          if [[ -n ${MODULES_ARG} ]]; then
            echo "Running modules: ${MODULES_ARG}"
            echo "MODULES_MAVEN_PARAM=[\" -pl ${MODULES_ARG}\"]" >> $GITHUB_OUTPUT
          else
            echo "MODULES_MAVEN_PARAM=[' -P root-modules,spring-modules,http-modules,test-tooling-modules', ' -P security-modules,sql-db-modules,messaging-modules,websockets-modules,monitoring-modules']" >> $GITHUB_OUTPUT
          fi
    outputs:
      MODULES_MAVEN_PARAM: ${{ steps.detect-modules-mvn-param.outputs.MODULES_MAVEN_PARAM }}
  linux-build-jvm-latest:
    name: PR - Linux - JVM build - Latest Version
    runs-on: ubuntu-latest
    timeout-minutes: 240
    needs: detect-jvm-latest-modules-mvn-param
    strategy:
      matrix:
        java: [ 11 ]
        module-mvn-args: ${{ fromJSON(needs.detect-jvm-latest-modules-mvn-param.outputs.MODULES_MAVEN_PARAM) }}
    steps:
      - name: Build with Maven
        run: |
          mvn -fae -V -B -s .github/mvn-settings.xml clean verify -Dall-modules -Dinclude.quarkus-cli-tests -Dts.quarkus.cli.cmd="${PWD}/quarkus-dev-cli"${{ matrix.module-mvn-args }} -am